name: "Tarefa / Task"
description: Para atividades técnicas, manutenção ou documentação.
title: "tarefa: [Título Curto]"
labels: ["geral"]
body:
  - type: markdown
    attributes:
      value: |
        ### Detalhes Técnicos
        Descreva a necessidade técnica, infraestrutura ou manutenção.

  - type: dropdown
    id: area-labels
    attributes:
      label: Área Responsável
      options:
        - Energia
        - Estrutura
        - Hardware
        - Software
    validations:
      required: true

  - type: dropdown
    id: type-labels
    attributes:
      label: Tipo de Tarefa
      options:
        - "Software (Desenvolvimento geral em src/)"
        - "Firmware (Código embarcado em src/firmware/)"
        - "Backend (Lógica de servidor em src/backend/)"
        - "Frontend (Interface de usuário em src/frontend/)"
        - "Hardware (Circuitos em hw/)"
        - "Mecânica (Projeto estrutural em mec/)"
        - "Refatoração / Limpeza"
        - "Bug"
        - "CAD (Modelagem de peças e estruturas)"
        - "Esquemático (Desenho de diagramas elétricos)"
        - "Simulação (Circuitos e sistemas dinâmicos)"
        - "Diagrama (Arquitetura e fluxogramas)"
        - "Design / Identidade Visual"
        - "Relatório (Escrita técnica profissional)"
        - "LaTeX (Formatação e compilação)"
        - "Orçamento (Levantamento de custos e BOM)"
        - "Documentação (Guias, READMEs e tutoriais)"
        - "Organização (Gestão de pastas e equipe)"
        - "Datasheet (Pesquisa técnica de componentes)"
        - "Infraestrutura"
        - "Segurança / Redes"
        - "Testes (Validação física e funcional)"
        - "Modelagem (Equações e modelos matemáticos)"
        - "Manufatura (Planejamento e montagem)"
        - "Prototipagem (Impressão 3D e fabricação rápida)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descrição da Demanda"
      placeholder: |
        Exemplo: 
        Configurar o ambiente de CI/CD para realizar o deploy automático da documentação MkDocs no GitHub Pages sempre que houver um push na main.
    validations:
      required: true

  - type: textarea
    id: technical-check
    attributes:
      label: "Passos / Critérios de Conclusão"
      description: "Itens técnicos que precisam ser validados."
      value: |
        - [ ] Criar arquivo .github/workflows/deploy.yml.
        - [ ] Configurar permissões de escrita do GITHUB_TOKEN.
        - [ ] Validar se o link do site está atualizando corretamente.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "Observações"
      placeholder: "Links de referência, logs de erro ou comandos específicos."
    validations:
      required: false
